### ISSUE TITLE
TODO and FIXME

### ISSUE THREAD

**Issue by gkeep** [gkeep/Authenticator#1]
`main.py`:

**TODO**:
- [ ] Finish GUI
   - [x] Optimize for multiple codes
   - [x] Add 'Add' and 'Remove' menus
      - [x] Add by inputting the values
      - [ ] ? Add QR code recognition
  - [ ] Add code copying on click
- [x] Display codes in groups 3

**FIXME**:
 - [x] Countdown clock and OTP code aren't synchronized
 - [x] Place account info and code after each other in column
 - [x] Codes don't refresh if remaining time is not 30 on launch
